### ISSUE TITLE
Strong Side Slams overpowered

### ISSUE THREAD

**Issue by kylebible** [Guitarbum722/volley-pong#2]
I'd like to discuss a rule change to limit the power of strong side slams.
In smaller (3v3 or 4v4) games, strong side slams can become overpowered, and limit the rhythm and competitiveness of the game.

I propose either incentivizing slams that are hit from behind the table by making them 2 points (see diagram),
or disincentivizing slamming from the side, by illiciting some kind of penalty (Keeping track of half points would be too complicated). 

Opening this issue to have a discussion about addressing this issue.

<img width="745" alt="Screen Shot 2019-09-19 at 3 27 46 PM" src="https://user-images.githubusercontent.com/26535855/65285800-60a6dd80-daf2-11e9-9b0e-d4b90393dd43.png">

**Comment by Anton1o-I** [comment]
If we want to limit slams, we could just not allow paddles to be higher then shoulder or head level at anytime in the game? 

Edit: Added a second option to appease Candy who would like to be able to continue protecting her face during a game.

**Comment by Guitarbum722** [comment]
Or you could just be better at jumping.

**Comment by danielvillela-myndshft** [comment]
When I played volleypong, there was one rule that was slightly different that made slams less frequent without detracting from the slams effectiveness. If someone touches the ball twice after everyone has touched it once, then you would have to "freeball" it over (underhand lob, just getting the ball over without intention of scoring point on the send). This would make it so that it rewards good passing and coordination and doesn't allow your team to just move the ball around on your side to give it to the power swinger to hit it over.

**Comment by Guitarbum722** [comment]
We played two matches using @Anton1o-I 's suggestion and that went pretty well.  How did every one else like it?

**Comment by Jason-Adam** [comment]
I like @Anton1o-I 's suggestion.  I vote for making that an official rule.
